site_name: MathExpr
site_url: https://sukeya.github.io/MathExpr/
repo_url: https://github.com/sukeya/MathExpr
edit_uri: blob/main/docs/
nav:
  - Home: index.md
  - Sections:
    - 00-introduction.md
    - 01-capabilities.md
    - 02-example-expressions.md
    - 03-copyright-notice.md
    - 04-downloads-and-updates.md
    - 05-installation.md
    - 06-compilation.md
    - 07-compiler-compatibility.md
    - 08-built-in-operations-and-functions.md
    - 09-fundamental-types.md
    - 10-components.md
    - 11-compilation-options.md
    - 12-expression-structures.md
    - 13-variable-vector-and-string-definition.md
    - 14-vector-processing.md
    - 15-user-defined-functions.md
    - 16-expression-dependents.md
    - 17-hierarchies-of-symbol-tables.md
    - 18-unknown-unknowns.md
    - 19-enabling-and-disabling-features.md
    - 20-expression-return-values.md
    - 21-compilation-errors.md
    - 22-runtime-library-packages.md
    - 23-helpers-and-utils.md
    - 24-runtime-checks.md
    - 25-benchmarking.md
    - 26-exprtk-notes.md
    - 27-simple-exprtk-example.md
    - 28-build-options.md
    - 29-files.md
    - 30-language-structure.md
theme:
  name: material
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.action.edit
    - toc.integrate
    - navigation.top
    - navigation.indexes
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - git-committers:
      repository: sukeya/MathExpr
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - glightbox
  - search
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
