[project]
name = "mathexpr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.10.2",
    "mkdocs-git-committers-plugin-2>=2.5.0",
    "mkdocs-git-revision-date-localized-plugin>=1.5.1",
    "mkdocs-glightbox>=0.5.2",
    "pymdown-extensions>=10.21.2",
    "zensical>=0.0.39",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "zensical>=0.0.39",
]
