name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.CI_DEPLOY }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Set up Zensical
        run: |
          sudo apt install curl
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
      - name: Build
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: uv run zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
